### ISSUE TITLE
Weird behavior with sftp

### ISSUE THREAD

**Issue by jmaassen** [NLeSC/xenon-cli#10]
After successfully running a job with slurm on fs0.das5 I wanted to copy back the stdout.txt produced by the job. This command:

    xenon sftp --location fs0.das5.cs.vu.nl download /home/jason/stdout.txt /home/jason/stdout.txt

does not produce the expected `stdout.txt` file locally. It's just not there, even though no error is given.

Strangely enough, if I replace the last `/home/jason/stdout.txt` with something else:

    xenon sftp --location fs0.das5.cs.vu.nl download /home/jason/stdout.txt /home/jason/wtf.txt

it works fine! The `wtf.txt` file contains a copy of `stdout.txt` on fs0.das5 as expected ....

**Comment by sverhoeven** [comment]
Debugged and found a premature return in Xenon if source and target paths are the same nothing happens, see https://github.com/NLeSC/Xenon/blob/master/src/main/java/nl/esciencecenter/xenon/engine/util/CopyEngine.java#L285-L287
