### ISSUE TITLE
Improve help docs

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/xenon-cli#36]
Some typo fixes, clarifications are needed.

**Comment by jspaaks** [comment]
- [ ] https://github.com/NLeSC/xenon-rse2017-tutorial/blob/10cff722c57e842e4380d1cbb7adc171208f9148/tutorial-commands.txt#L18
- [ ] https://github.com/NLeSC/xenon-rse2017-tutorial/blob/10cff722c57e842e4380d1cbb7adc171208f9148/tutorial-commands.txt#L115
- [ ] https://github.com/NLeSC/xenon-rse2017-tutorial/blob/10cff722c57e842e4380d1cbb7adc171208f9148/tutorial-commands.txt#L182
- [ ] https://github.com/NLeSC/xenon-rse2017-tutorial/blob/10cff722c57e842e4380d1cbb7adc171208f9148/tutorial-commands.txt#L220
- [ ] https://github.com/NLeSC/xenon-rse2017-tutorial/blob/10cff722c57e842e4380d1cbb7adc171208f9148/tutorial-commands.txt#L241
