### ISSUE TITLE
Rename target-location argument to --target-location

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/xenon-cli#43]
Then credential and location argument are together

**Comment by jspaaks** [comment]
e.g. 
- https://github.com/NLeSC/xenon-rse2017-tutorial/blob/262a30eeebe93d28ab2b940a43999ebeb75b1b01/tutorial-commands.txt#L307
- https://github.com/NLeSC/xenon-rse2017-tutorial/blob/262a30eeebe93d28ab2b940a43999ebeb75b1b01/tutorial-commands.txt#L313
