### ISSUE TITLE
Create a conda package for xenon-cli

### ISSUE THREAD

**Issue by arnikz** [NLeSC/xenon-cli#49]

**Comment by sverhoeven** [comment]
Working on it in https://github.com/NLeSC/xenon-cli/tree/conda

**Comment by sverhoeven** [comment]
Rough first version on https://anaconda.org/nlesc/xenon-cli

Todo:
* should it be part of conda-forge 
* instead of manual build+upload use feedstock automation

**Comment by sverhoeven** [comment]
Now building a noarch, but this does not work under Windows because the xenon.bat is not part of build.

So either go with linux64 only or go multiple archs. Multiple archs requires ci servers to build for the different archs. Like is done at conda-forge

**Comment by sverhoeven** [comment]
For now manually building linux-64 arch. If other arches are needed then open an issue.
