### ISSUE TITLE
Can't list available queues

### ISSUE THREAD

**Issue by arnikz** [NLeSC/xenon-cli#51]
I'm logged to the head node (related to #50):

```
$ xenon scheduler gridengine --location local:// queues
gridengine adaptor: Cannot parse slots for queue "test.q", got "12,[@cores_36=36],[@cores_12=12],[@cores_48=48], \"
```

**Comment by sverhoeven** [comment]
Same underlying problem as #50, will be solved in https://github.com/NLeSC/Xenon/issues/606

**Comment by jmaassen** [comment]
Working on https://github.com/NLeSC/Xenon/issues/606 now

**Comment by jmaassen** [comment]
Fixed in current Xenon master

**Comment by arnikz** [comment]
Sorry, I've got the same error. Is this _xenon_ fix also "propagated" to _xenon-cli_?

**Comment by sverhoeven** [comment]
It's propagated when we completed the steps described at https://github.com/NLeSC/xenon-cli/issues/52#issuecomment-361599808

**Comment by arnikz** [comment]
OK, I'll be patient:)

**Comment by arnikz** [comment]
Works like a charm with the new release!
