### ISSUE TITLE
Fails to submit job(s) to a user-specified queue

### ISSUE THREAD

**Issue by arnikz** [NLeSC/xenon-cli#52]
We've seen this one previously (related #51).

```
xenon scheduler gridengine --location local://$PWD submit --queue all.q ...
gridengine adaptor: Cannot parse slots for queue "test.q", got "12,[@cores_36=36],[@cores_12=12],[@cores_48=48], \
```

**Comment by jmaassen** [comment]
Fixed in current xenon master

**Comment by arnikz** [comment]
Thank! B.t.w. is this also available via the `nlesc` conda channel? If not I'll take the longer route;)

**Comment by sverhoeven** [comment]
No, it's not yet available on conda we still need to
1. [ ] Create a new release of Xenon
2. [ ] Create a new release of xenon-cli, which depends on the new Xenon release
3. [ ] Build & upload conda package of the new xenon-cli release

**Comment by jmaassen** [comment]
I'll create a new release of Xenon

**Comment by jmaassen** [comment]
Release 2.3.0 is done

**Comment by arnikz** [comment]
OK. I'm on it...but something missing from my env as my jobs keep failing.

**Comment by sverhoeven** [comment]
xenon-cli on conda has been updated with slot fix

**Comment by arnikz** [comment]
It works now with the new release!
