### ISSUE TITLE
Add option to run OpenMP threaded jobs

### ISSUE THREAD

**Issue by arnikz** [NLeSC/xenon-cli#57]

**Comment by arnikz** [comment]
xenon-cli options:
with SGE: `--option parallel.environment=threaded --option parallel.slots=...`
with SLURM: ? (should use `--cpus-per-task`)

It would be nice to have single option common to both (all) schedulers so that the `xenon` command requires a single change only i.e. `gridengine` or `slurm`. One could "harmonizes" the options across schedulers using e.g. a config file (incl. additional details or mappings).

**Comment by jmaassen** [comment]
A bit more info on translating the various options:

https://slurm.schedmd.com/rosetta.pdf

**Comment by arnikz** [comment]
I've used a similar conversion table for my use case (see [here](https://srcc.stanford.edu/sge-slurm-conversion)) but it did not work with my OpenMP program so I've followed [this](https://arcs.virginia.edu/slurm) suggestion, which worked fine:)
